# Generated by Django 4.0.1 on 2022-01-26 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('created_by_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_url', models.URLField(default='')),
                ('ship_to_address', models.CharField(max_length=120)),
            ],
        ),
    ]
