# Generated by Django 4.0.1 on 2022-01-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': 'QRCode', 'verbose_name_plural': 'QRCodes'},
        ),
        migrations.AlterModelTable(
            name='qrcode',
            table='QRCode',
        ),
    ]
