# Generated by Django 4.0.1 on 2022-01-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_alter_qrcode_options_alter_qrcode_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='created_by_user',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='associated_user',
            field=models.CharField(default='None', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='profile_url',
            field=models.URLField(),
        ),
    ]
