# Generated by Django 4.0.1 on 2022-01-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_remove_qrcode_created_by_user_qrcode_associated_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='ship_to_address',
        ),
    ]
