# Generated by Django 4.0.2 on 2022-03-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
