# Generated by Django 4.0.1 on 2022-01-21 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_person_options_alter_person_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
