# Generated by Django 4.0.1 on 2022-01-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
