# Generated by Django 4.0.1 on 2022-02-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code_img',
            field=models.ImageField(default='qr_code/default.png', upload_to=''),
        ),
    ]
