# Generated by Django 4.0.1 on 2022-02-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_link_url',
            field=models.URLField(default='This user has not provided a donation link.'),
        ),
    ]
