# Generated by Django 4.0.1 on 2022-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='', upload_to='profile_img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='life_story',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_url',
            field=models.URLField(),
        ),
    ]
