# Generated by Django 4.0.1 on 2022-02-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_scan_count',
            field=models.IntegerField(default=0),
        ),
    ]
