# Generated by Django 4.0.1 on 2022-02-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_qr_code_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code_img',
            field=models.ImageField(upload_to='qr_code'),
        ),
    ]
