# Generated by Django 4.0.1 on 2022-02-14 21:34

from django.db import migrations, models
from localflavor.us.models import USStateField


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=USStateField(default="NC", blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default="Raleigh", max_length=60),
        ),
    ]
