# Generated by Django 4.0.2 on 2022-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_phone_number_profile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
