# Generated by Django 4.0.1 on 2022-02-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_payment_link_url copy'),
        ('user', '0004_add_city_state'),
    ]

    operations = [
    ]
