# Generated by Django 4.0.1 on 2022-02-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_qr_code_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code_img',
            field=models.FilePathField(max_length=150),
        ),
    ]
