# Generated by Django 4.0.1 on 2022-02-15 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile_img/default.jpg', storage=user.models.OverwriteStorage(), upload_to=user.models.UploadToPathAndRename(models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL), 'profile_img/')),
        ),
    ]
