# Generated by Django 4.0.2 on 2022-10-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_accepted_terms_and_conditions'),
        ('user', '0009_alter_profile_profile_url'),
    ]

    operations = [
    ]
