# Generated by Django 4.0.2 on 2022-10-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_url',
            field=models.CharField(max_length=200),
        ),
    ]
