# Generated by Django 4.0.2 on 2022-10-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20221025_1851'),
        ('user', '0011_alter_profile_profile_url'),
    ]

    operations = [
    ]
