# Generated by Django 4.0.2 on 2022-03-26 14:23

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f7e43d28850> <django.db.models.query_utils.DeferredAttribute object at 0x7f7e43d28790>', max_length=50)),
                ('state', localflavor.us.models.USStateField(default='NC', max_length=2)),
                ('city', models.CharField(default='Raleigh', max_length=50)),
                ('zipcode', localflavor.us.models.USZipCodeField(default='27513', max_length=10)),
                ('street', models.CharField(default='100 ABC st\n<django.db.models.fields.CharField>, <localflavor.us.models.USStateField>\n<localflavor.us.models.USZipCodeField>', max_length=99)),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
                'db_table': 'Sticker',
            },
        ),
    ]
