# Generated by Django 4.0.2 on 2022-02-22 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('ship_to_address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', localflavor.us.models.USStateField(default='', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(default=27587, max_length=10)),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
                'db_table': 'Sticker',
            },
        ),
    ]
