# Generated by Django 4.0.2 on 2022-03-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_alter_sticker_options_alter_sticker_full_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sticker',
            new_name='StickerShipment',
        ),
    ]
