# Generated by Django 4.0.2 on 2022-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_rename_sticker_stickershipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickershipment',
            name='street',
        ),
        migrations.AddField(
            model_name='stickershipment',
            name='street_name_and_number',
            field=models.CharField(default='100 ABC st', max_length=99),
        ),
    ]
