# Generated by Django 4.0.2 on 2022-04-17 21:49

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_remove_stickershipment_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickershipment',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stickershipment',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stickershipment',
            name='state',
            field=localflavor.us.models.USStateField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stickershipment',
            name='street_name_and_number',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AlterField(
            model_name='stickershipment',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(default='', max_length=10),
        ),
    ]
